name: Node.js Release Workflow

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Install dependencies using npm ci
        run: npm ci

      - name: Create Release Pull Request or Publish
        id: changesets
        uses: changesets/action@v1
        with:
            publish: npm run release
        env:
          GITHUB_TOKEN: ${{secrets.CI_TOKEN}}
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}